[package]
name = "tcp-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
uuid = "0.8"
tokio = { version = "1.16.1", features = ["full"] }
async-trait = "0.1.52"